language: python

dist: focal

python:
  - "3.8"

before_install:
  - sudo apt-get install -y libfreetype6-dev libglib2.0-dev libcairo2-dev libharfbuzz-dev

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .

script:
  - (cd tests && ./run.sh)
